-- ####################################################################
-- ######################## CASE STUDY QUERIES #########################
-- ####################################################################

USE sales_case_study;

-- =========================================================
-- TASK 1
-- Display the number of states present in the LocationTable
-- =========================================================
select Count(distinct state) as num_of_states
from locationtable;

-- =========================================================
-- TASK 2
-- How many products are of regular type?
-- =========================================================

select Sum(case when Type='Regular' then 1 else 0 end ) as regular_products_count
from producttable;

-- =========================================================
-- TASK 3
-- How much spending has been done on marketing of ProductID 1?
-- =========================================================
select total_expenses
from facttable
where productId=1;

-- =========================================================
-- TASK 4
-- What is the minimum sales of a product?
-- =========================================================
select MIN(sales) as minimum_sale_for_product
from facttable;

-- =========================================================
-- TASK 5
-- Display the maximum Cost Of Goods Sold (COGS)
-- =========================================================
select MAX(COGS) as maximum_cost_of_goods_sold
from facttable;

-- =========================================================
-- TASK 6
-- Display the details of the product where ProductType is Coffee
-- =========================================================
select * from producttable
where ProductType='Coffee';

-- =========================================================
-- TASK 7
-- Display the details where Total Expenses are greater than 40
-- =========================================================
select *
from facttable
where Total_Expenses>40;

-- =========================================================
-- TASK 8
-- What is the average sales in Area Code 719?
-- =========================================================
select AVG(sales) as avg_sales from facttable
where Area_Code=719;

-- =========================================================
-- TASK 9
-- Find out the total profit generated by Colorado state
-- =========================================================
select l.state,SUM(f.profit) as total_profit 
from facttable f join locationtable l
on f.Area_Code=l.Area_Code
where state='Colorado'
group by l.State;

-- =========================================================
-- TASK 10
-- Display the average inventory for each ProductID
-- =========================================================
select ProductID,AVG(Inventory) as avg_inventory 
from facttable
group by ProductID;

-- =========================================================
-- TASK 11
-- Display states in sequential order in the LocationTable
-- =========================================================
select state from locationtable
order by state asc;

-- =========================================================
-- TASK 12
-- Display the average budget margin where average budget margin
-- should be greater than 100
-- =========================================================
select ProductID,avg(budget_margin) as avg_budget_margin 
from facttable
group by ProductID
having avg(Budget_Margin)>100;

-- =========================================================
-- TASK 13
-- What is the total sales done on date 2010-01-01?
-- =========================================================
select date_format(date,'%Y-%m') as date,SUM(sales) as total_sales 
from facttable
where date='2010-01-01'
group by date;

-- =========================================================
-- TASK 14
-- Display the average total expenses of each ProductID
-- on an individual date
-- =========================================================
select productID,date_format(date,'%Y-%m') as date,avg(total_expenses) as avg_total_expense
from facttable
group by ProductID,date;
-- =========================================================
-- TASK 15-- Display the table with the following attributes:
-- Date, ProductID, ProductType, Product, Sales,-- Profit, State, Area_Code
-- ========================================================
select f.date,f.productid,p.producttype,p.product,f.sales,f.profit,l.state,f.area_code
from facttable f join producttable p
on f.ProductID=p.ProductID
join locationtable l on l.Area_Code=f.Area_Code;
-- =========================================================
-- TASK 16
-- Display the rank without any gap to show the sales-wise rank
-- =========================================================
select f.productID,p.product,f.sales,rank() over (order by f.sales desc) as sales_rank
from facttable f join producttable p
on f.ProductID=p.ProductID;
-- =========================================================
-- TASK 17
-- Find the state-wise profit and sales
-- =========================================================
select l.state, SUM(f.profit) as total_profit, SUM(sales) as total_sales
from facttable f join locationtable l
on l.Area_Code=f.Area_Code
group by l.State;
-- =========================================================
-- TASK 18
-- Find the state-wise profit and sales along with product name
-- =========================================================
select p.product,l.state, SUM(f.profit) as total_profit, SUM(sales) as total_sales
from facttable f join locationtable l
on l.Area_Code=f.Area_Code
join producttable p
on f.ProductID=p.ProductID
group by l.State,p.Product;
-- =========================================================
-- TASK 19
-- If there is an increase in sales of 5%,
-- calculate the increased sales
-- =========================================================
select productID,sales,sales+sales*0.05 as increased_sales
from facttable;

-- =========================================================
-- TASK 20
-- Find the maximum profit along with ProductID
-- and ProductType
-- =========================================================
select f.productID,P.Producttype,max(f.profit) as maximum_profit
from facttable f join producttable p
on f.ProductID=p.ProductID
group by f.productID,P.Producttype;

-- =========================================================
-- TASK 21
-- Create a stored procedure to fetch the result
-- according to the ProductType from ProductTable
-- =========================================================
/*CREATE DEFINER=`root`@`localhost` PROCEDURE `get_type_of_product`(in ptype varchar(25))
BEGIN
select *
from producttable
where ProductType=ptype;
END*/
CALL get_type_of_product('Coffee');
-- =========================================================
-- TASK 22
-- Create a condition:
-- If Total_Expenses is less than 60 then 'Profit'
-- else 'Loss'
-- =========================================================
select ProductID,Total_Expenses,
case when Total_Expenses<60 then 'loss '
else 'profit' end as  Profit_or_Loss
from facttable;
-- =========================================================
-- TASK 23
-- Give the total weekly sales value with Date
-- and ProductID details using ROLLUP
-- =========================================================
select productId, date,sum(sales) as total_weekly_sales
from facttable
GROUP BY Date, ProductID WITH ROLLUP;
-- =========================================================
-- TASK 24
-- Apply UNION and INTERSECTION operator on tables
-- consisting of Area_Code attribute
-- =========================================================
select Area_Code from facttable
union
select Area_Code from locationtable;

select distinct f.area_code
from facttable f join locationtable l
ON f.Area_Code = l.Area_Code;
-- =========================================================
-- TASK 25
-- Create a user-defined function for ProductTable
-- to fetch a particular ProductType based on user preference
-- =========================================================
/*CREATE DEFINER=`root`@`localhost` FUNCTION `get_product_type`(p_ProductID int) RETURNS varchar(100) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
 DECLARE v_ProductType VARCHAR(20);

    SELECT ProductType
    INTO v_ProductType
    FROM ProductTable
    WHERE ProductID = p_ProductID;

    RETURN v_ProductType;

END*/
SELECT ProductID, get_product_type(ProductID) AS Product_Type
FROM ProductTable;

-- =========================================================
-- TASK 26
-- Change the ProductType from Coffee to Tea
-- where ProductID is 1 and undo it
-- =========================================================
START TRANSACTION;

update producttable
set ProductType='Tea'
where ProductID = 1;
-- check change
SELECT * FROM ProductTable WHERE ProductID = 1;

-- UNDO (rollback)
ROLLBACK;
-- =========================================================
-- TASK 27
-- Display Date, ProductID and Sales where
-- Total_Expenses are between 100 and 200
-- =========================================================
select date,productId,sales
from facttable 
where Total_Expenses between 100 and 200;

-- =========================================================
-- TASK 28
-- Delete the records in ProductTable
-- for Regular type products
-- =========================================================
delete from producttable
where ProductType='Regular';
-- =========================================================
-- TASK 29
-- Display the ASCII value of the fifth character
-- from the column Product
-- =========================================================
SELECT Product,ASCII(SUBSTRING(Product, 5, 1)) AS Fifth_Character_ASCII
FROM ProductTable;